# This is a pre-release of a Helm 2to3 migration template to facilitate
# the migration of Auto DevOps releases to Helm 3.

.helm-2to3:
  image: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image/releases/helm-2to3-2.16.9-3.2.4-kube-1.13.12
  # TODO: Do we need a new stage? This stage is not used any Auto DevOps template, but the name is misleading
  stage: deploy
  needs: []
  environment:
    action: prepare
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - backups/
  before_script:
    - set -e
    - apk add jq
    - export TILLER_NAMESPACE=$KUBE_NAMESPACE
    - export HELM_HOST="localhost:44134"
    - nohup tiller -listen "${HELM_HOST}" >tiller.log 2>&1 &
    - helm2 init --client-only
    # TODO: Move this to the job image
    - helm2 plugin install https://github.com/maorfr/helm-backup
  script:
    - |
      for release in $(helm2 ls --output json | jq '.Releases[].Name')
        helm2 backup "$release" --file "backup/$release"
        helm3 2to3 convert --release-storage configmaps --tiller-out-cluster --tiller-ns "$KUBE_NAMESPACE" "$release"
      done
    - helm3 2to3 cleanup --skip-confirmation --release-storage configmaps --tiller-out-cluster --tiller-ns "$KUBE_NAMESPACE"

review:helm-2to3:
  extends: .helm-2to3
  environment:
    name: review/$CI_COMMIT_REF_NAME
  rules:
    - if: '$MIGRATE_HELM_2TO3 != "true"'
      when: never
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: never
    - if: '$REVIEW_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'
      when: manual

staging:helm-2to3:
  extends: .helm-2to3
  environment:
    name: staging
  rules:
    - if: '$MIGRATE_HELM_2TO3 != "true"'
      when: never
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$STAGING_ENABLED'
      when: manual

production:helm-2to3:
  extends: .helm-2to3
  environment:
    name: production
  rules:
    - if: '$MIGRATE_HELM_2TO3 != "true"'
      when: never
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
